### ISSUE TITLE
Test the new Apache connector

### ISSUE THREAD

**Issue by sirocchj** [laserdisc-io/zio-oci-objectstorage#58]
As per #50 we wanted to ensure no breaking changes are getting introduced by new releases of the oci libs. Specifically, there were changes introduced in 2.0.0 that could impact negatively our use cases. This ticket is to keep track of the need to add some specific tests to ensure that's not the case.

Note that Tamer, which uses zio-oci-objectstorage under the hood, has already updated to 2.x series in its 0.10.0 release (see https://github.com/laserdisc-io/tamer/pull/423)

**Comment by amir** [comment]
Addressed in #81
